"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";

type Aggregate = { carrier:string; origin:string; destination:string; flights:number; delayed_flights:number; total_delay_minutes:number };
type Analytics = { overview:{flights:number;delay_rate:number;average_delay:number}; options:{carriers:string[];origins:string[];destinations:string[]}; route_aggregates:Aggregate[]; metrics:Record<string,number|string> };
const names:Record<string,string>={AA:"American",AS:"Alaska",B6:"JetBlue",DL:"Delta",F9:"Frontier",G4:"Allegiant",NK:"Spirit",UA:"United",WN:"Southwest"};
const pct=(n:number)=>`${n.toFixed(1)}%`;

export default function Dashboard(){
 const [data,setData]=useState<Analytics|null>(null),[error,setError]=useState("");
 const [carrier,setCarrier]=useState("All"),[origin,setOrigin]=useState("All"),[destination,setDestination]=useState("All");
 const [prediction,setPrediction]=useState(""),[predicting,setPredicting]=useState(false);
 useEffect(()=>{fetch("/data/overview.json").then(r=>{if(!r.ok)throw Error("The analytics summary could not be loaded.");return r.json()}).then(setData).catch(e=>setError(e.message))},[]);
 const filtered=useMemo(()=>data?.route_aggregates.filter(r=>(carrier==="All"||r.carrier===carrier)&&(origin==="All"||r.origin===origin)&&(destination==="All"||r.destination===destination))??[],[data,carrier,origin,destination]);
 const summary=useMemo(()=>{const flights=filtered.reduce((s,r)=>s+r.flights,0),delayed=filtered.reduce((s,r)=>s+r.delayed_flights,0),minutes=filtered.reduce((s,r)=>s+r.total_delay_minutes,0);return{flights,rate:flights?delayed/flights*100:0,delay:flights?minutes/flights:0}},[filtered]);
 const carriers=useMemo(()=>{const map=new Map<string,{flights:number;delayed:number}>();filtered.forEach(r=>{const x=map.get(r.carrier)??{flights:0,delayed:0};x.flights+=r.flights;x.delayed+=r.delayed_flights;map.set(r.carrier,x)});return[...map].map(([code,x])=>({code,...x,rate:x.delayed/x.flights*100})).sort((a,b)=>b.rate-a.rate)},[filtered]);
 const routes=useMemo(()=>{const map=new Map<string,{origin:string;destination:string;flights:number;delayed:number}>();filtered.forEach(r=>{const key=`${r.origin}-${r.destination}`,x=map.get(key)??{origin:r.origin,destination:r.destination,flights:0,delayed:0};x.flights+=r.flights;x.delayed+=r.delayed_flights;map.set(key,x)});return[...map.values()].filter(r=>r.flights>=10).map(r=>({...r,rate:r.delayed/r.flights*100})).sort((a,b)=>b.rate-a.rate).slice(0,10)},[filtered]);
 async function predict(e:FormEvent<HTMLFormElement>){e.preventDefault();setPredicting(true);setPrediction("");try{const body=Object.fromEntries(new FormData(e.currentTarget));const r=await fetch("/api/predict",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});if(!r.ok)throw Error();const result=await r.json();setPrediction(pct(result.delay_probability*100))}catch{setPrediction("Prediction API is not connected yet") }finally{setPredicting(false)}}
 if(error)return <main className="state-page"><h1>FlightPulse could not load</h1><p>{error}</p><button onClick={()=>location.reload()}>Try again</button></main>;
 if(!data)return <main className="state-page"><span className="loader"/><h1>Loading flight intelligence…</h1><p>Preparing the national delay summary.</p></main>;
 const m=data.metrics;
 return <main>
  <header className="site-header"><a className="brand" href="#top"><span className="brand-mark">FP</span><span>FlightPulse</span></a><nav><a href="#analytics">Explore</a><a href="#model">Model</a><a className="nav-cta" href="#prediction">Check a flight</a></nav></header>
  <section className="hero" id="top"><div className="hero-copy"><span className="eyebrow">U.S. flight intelligence · April–May 2026</span><h1>See delay patterns before you reach the gate.</h1><p>Explore 1.3 million official flight records and estimate the chance of a departure delay using a chronologically evaluated machine-learning model.</p><div className="hero-actions"><a className="button primary" href="#analytics">Explore the data</a><a className="button secondary" href="#model">How the model works</a></div><p className="source-note">Official U.S. Bureau of Transportation Statistics data</p></div><div className="hero-visual"><div className="route-card"><div className="route-topline"><span>DELAY SIGNAL</span><span className="status-dot">HISTORICAL DATA</span></div><div className="route-airports"><div><strong>DTW</strong><span>Detroit</span></div><div className="route-line"><span>✦</span></div><div><strong>JFK</strong><span>New York</span></div></div><div className="risk-strip"><span>Dataset delay rate</span><strong>{pct(data.overview.delay_rate)}</strong></div></div><div className="grid-glow"/></div></section>
  <section className="content-section" id="analytics"><div className="section-heading"><div><span className="eyebrow">Historical performance</span><h2>Explore the national picture</h2></div><p>Non-cancelled departures · Apr 1–May 31, 2026</p></div>
   <div className="filter-bar"><label>Carrier<select value={carrier} onChange={e=>setCarrier(e.target.value)}><option>All</option>{data.options.carriers.map(x=><option key={x}>{x}</option>)}</select></label><label>Origin<select value={origin} onChange={e=>setOrigin(e.target.value)}><option>All</option>{data.options.origins.map(x=><option key={x}>{x}</option>)}</select></label><label>Destination<select value={destination} onChange={e=>setDestination(e.target.value)}><option>All</option>{data.options.destinations.map(x=><option key={x}>{x}</option>)}</select></label><button onClick={()=>{setCarrier("All");setOrigin("All");setDestination("All")}}>Reset filters</button></div>
   {!summary.flights?<div className="empty-state"><h3>No matching flights</h3><p>Change or reset one of the filters.</p></div>:<><div className="metric-grid"><article className="metric-card accent-card"><span>Analyzed flights</span><strong>{summary.flights.toLocaleString()}</strong><small>Matching official records</small></article><article className="metric-card"><span>Delayed 15+ minutes</span><strong>{pct(summary.rate)}</strong><small>Selected flights</small></article><article className="metric-card"><span>Average departure delay</span><strong>{summary.delay.toFixed(1)} min</strong><small>Early departures included</small></article><article className="metric-card"><span>Holdout ROC-AUC</span><strong>{Number(m.roc_auc).toFixed(3)}</strong><small>Model evaluation</small></article></div>
   <div className="insight-grid"><article className="panel"><div className="panel-heading"><div><span className="panel-kicker">Carrier comparison</span><h3>Delay rates</h3></div><span className="panel-chip">15+ min delay</span></div><div className="bar-list">{carriers.map(r=><div className="bar-row" key={r.code}><div className="bar-label"><strong>{r.code}</strong><span>{names[r.code]}</span></div><div className="bar-track"><span style={{width:`${Math.min(r.rate/35*100,100)}%`}}/></div><strong className="bar-value">{pct(r.rate)}</strong></div>)}</div></article>
   <article className="panel route-panel"><div className="panel-heading"><div><span className="panel-kicker">Route comparison</span><h3>Highest delay rates</h3></div><span className="panel-chip">10+ flights</span></div><div className="route-table">{routes.map((r,i)=><div key={`${r.origin}-${r.destination}`}><span>{i+1}</span><strong>{r.origin} → {r.destination}</strong><small>{r.flights.toLocaleString()} flights</small><b>{pct(r.rate)}</b></div>)}</div></article></div></>}
  </section>
  <section className="model-section" id="model"><div className="section-heading"><div><span className="eyebrow">Honest evaluation</span><h2>Tested on later flights</h2></div><p>Trained on April · tested on May</p></div><div className="model-grid"><article className="panel model-summary"><span className="panel-kicker">Selected model · Random forest</span><h3>0.688 ROC-AUC on a 670K-flight holdout.</h3><p>The chronological split asks the model to predict a later month it did not train on. It is more realistic than mixing future flights into training, but two months do not prove year-round performance.</p><div className="model-stat-row"><div><span>Recall</span><strong>{pct(Number(m.recall)*100)}</strong></div><div><span>Precision</span><strong>{pct(Number(m.precision)*100)}</strong></div><div><span>F1</span><strong>{pct(Number(m.f1_score)*100)}</strong></div></div></article><article className="panel confusion"><span className="panel-kicker">Confusion matrix · May holdout</span><h3>What the predictions got right and wrong</h3><div className="matrix"><div><span>Correct on time</span><strong>{Number(m.true_negatives).toLocaleString()}</strong></div><div className="warm"><span>False alarm</span><strong>{Number(m.false_positives).toLocaleString()}</strong></div><div className="warm"><span>Missed delay</span><strong>{Number(m.false_negatives).toLocaleString()}</strong></div><div className="dark"><span>Correct delay</span><strong>{Number(m.true_positives).toLocaleString()}</strong></div></div></article></div></section>
  <section className="prediction-preview" id="prediction"><div><span className="eyebrow">Delay-risk model</span><h2>Check a scheduled flight.</h2><p>Choose the same six inputs used by the trained model. This is an estimate based on historical patterns—not live operational data.</p>{prediction&&<div className="prediction-result" aria-live="polite"><span>Estimated delay probability</span><strong>{prediction}</strong></div>}</div><form className="prediction-form" onSubmit={predict}><label>Carrier<select name="carrier" defaultValue="AA">{data.options.carriers.map(x=><option key={x}>{x}</option>)}</select></label><label>Origin<select name="origin" defaultValue="DTW">{data.options.origins.map(x=><option key={x}>{x}</option>)}</select></label><label>Destination<select name="destination" defaultValue="JFK">{data.options.destinations.map(x=><option key={x}>{x}</option>)}</select></label><label>Departure hour<input name="hour" type="number" min="0" max="23" defaultValue="12"/></label><label>Month<input name="month" type="number" min="1" max="12" defaultValue="6"/></label><label>Day<select name="day_of_week">{["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"].map((x,i)=><option value={i} key={x}>{x}</option>)}</select></label><button disabled={predicting}>{predicting?"Estimating…":"Estimate delay risk"}</button></form></section>
  <footer><span>FlightPulse</span><span>Official BTS data · Not live flight status</span></footer>
 </main>
}
